# gitops/argocd/applications/myapp.yaml
# kubectl apply -f gitops/argocd/applications/myapp.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jinxin-wang/gitops-infra
    targetRevision: main
    path: gitops/apps/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true